# 
- name: install Docker to all cluster hosts
  hosts: docker-swarm
  gather_facts: false

# Yum install package
  tasks:
  - name: Install common software requirements
    become: true
    yum:
      state: installed
      name: 
        - lvm2
        - device-mapper-persistent-data
        - yum-utils
# Yum install package
  - name: Update docker repo
    command: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: Update repos
    command: yum update -y
  - name: Install docker packages
    yum: 
      state: installed
      name: 
       - docker-ce
       - docker-ce-cli
       - containerd.io

 
